licenses(["notice"])  # Apache 2.0

# Files used for internal continuous benchmark testing.
filegroup(
    name = "files",
    srcs = [
        "extension.js",
        "index.js",
        "index.js.map",
        "vulcanized_template.html",
    ],
    visibility = ["//tensorflow_model_analysis:__subpackages__"],
)
