# Github action definitions for unit-tests with PRs.

name: tfma-unit-tests
on:
  push:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

env:
  USE_BAZEL_VERSION: 7.7.0

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          setup.py

    - name: Remove buggy sitecustomize
      run: |
        sudo find /etc/ -name "*sitecustomize*" -print -delete || true
        sudo find /usr/ -name "*sitecustomize*" -print -delete || true
        sudo find /opt/ -name "*sitecustomize*" -print -delete || true
        sudo find /home/runner/ -name "*sitecustomize*" -print -delete || true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler
        pip install --upgrade pip setuptools wheel numpy pyarrow
        pip install --no-build-isolation .

    - name: Run unit tests
      shell: bash
      run: |
        python -m unittest discover -p "*_test.py"
